# Key metadata about the site
site_name: Endeavour Predict
site_description: Website and documentation for the Endeavour Predict API service
site_author: Endeavour Health Charitable Trust
site_url:

# MkDocs processes files in this folder into a HTML site
docs_dir: docs

# Copyright information which is shown in the footer
copyright: Copyright &copy; 2023 Endeavour Health Charitable Trust

# these lines configure the 'GitHub repo' widget on the top right
repo_url: https://github.com/endeavour-predict/endeavourpredict.org
repo_name: endeavourpredict.org
edit_uri: blob/main/docs

# `mkdocs serve` serves the docs locally on this port
dev_addr: "127.0.0.1:8001"

# Navigation structure
nav:
  - Home: index.md
  - About:
    - About Us: about/index.md
    - Strategy: about/strategy.md
  - 'QRisk3':
      - "qrisk3/qrisk3.md"
    # - "clinical-safety-management-system.md"
    # - "clinical-safety-management-plan.md"
    # - "clinical-safety-case-report.md"
    # - "hazard-log.md"
    # - "business-continuity.md"
    # - "security.md"
    # - "third-party-tools-safety-assmt.md"
    # - "medical-device.md"
    # - "download.md"
    # - "contact.md"
    # - "license.md"

# theme settings, fonts, colours
theme:
  name: material
  custom_dir: endeavour-theme
  
  # replace these path or the contents of the files to change the logo and favicon
  logo: _assets/_images/logo.png
  favicon: _assets/_images/favicon.png

  features:
    - content.action.edit
    - navigation.expand
    - navigation.instant
    # uncomment the below two lines for Tabbed navigation (along the header bar)
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    # - toc.integrate
    - toc.follow

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    code: Roboto Mono
    
  icon:
    edit: material/pencil 
    view: material/eye


# mkdocs plugins
plugins:
  - git-committers:
      repository: https://github.com/endeavour-predict/www.endeavour-predict.net
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - with-pdf:
        #cover: false
        #back_cover: true
        #cover_subtitle: SUBTITLE TEXT
        #custom_template_path: TEMPLATES PATH
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
      output_path: pdf/endeavour-predict-clinical-safety-management-file.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #show_anchors: true
        #verbose: true


# additional markdown features
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true

# set extra CSS file
extra_css:
  - _assets/_stylesheets/extra.css

extra:
  project_slug: endeavour-predict
  
  # uncomment to add social icons
  # social:
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/exampleorgstwitter
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/exampleorgsgithub